import { useState, useEffect } from "react";

const table = Object.freeze(
    {
        "en": {
            add: "Add",
            alreadyRegistered: "Already registered? Login!",
            back: "Back",
            backToHome: "Back to Home",
            cancel: "Cancel",
            changeAvatar: "Change Avatar",
            chooseAvatar: "Choose Avatar",
            chooseSize: "Choose size",
            connecting: "Connecting...",
            couldNotConnectToServer: "Could not connect to the server",
            createNewUser: "Create new user",
            defeat: "Defeat",
            disable: "Disable",
            disableTwoFactor: "Disable Two-Factor Authentication",
            displayName: "Display Name",
            duplicateUser: "This user is already logged in. Please use a different account.",
            edit: "Edit",
            email: "Email",
            enable: "Enable",
            enableTwoFactor: "Enable Two-Factor Authentication",
            enterImageUrl: "Enter an Image URL",
            enterImageUrlPlaceholder: "https://example.com/my-avatar.png",
            enterSixDigitCode: "Enter the 6-digit code from your authenticator app",
            failedToLoadProfile: "Failed to load profile",
            findPeople: "Find People",
            fourPlayers: "4 players",
            friends: "Friends",
            howDoYouWantToPlay: "How do you want to play?",
            incoming: "Incoming",
            intro: "Let's get ready to play!",
            invalidCode: "Invalid code. Please try again.",
            loading: "Loading...",
            logIn: "Log In",
            login: "Login",
            logOut: "Log Out",
            logout: "Logout",
            loginOrSignupPlayer: "Login or Signup Player",
            loss: "Loss",
            losses: "Losses",
            manualEntry: "Or enter this secret manually:",
            matchHistory: "Match History",
            memberSince: "Member since",
            next: "Next",
            noFriendsYet: "No friends yet",
            noGamesYet: "No games played yet.",
            noNewUsersFound: "No new users found.",
            noRequests: "No requests",
            notRegisteredYet: "Not registered yet? Sign up!",
            oneVsOne: "1 vs 1",
            or: "OR",
            outgoing: "Outgoing",
            password: "Password",
            pleaseLoginToViewProfile: "Please log in to view your profile",
            popupBlocked: "Popup blocked. Please allow popups.",
            profile: "Profile",
            removeFriendConfirm: "Remove this friend?",
            requests: "Requests",
            save: "Save",
            scanQRCode: "Scan this QR code with your authenticator app (Google Authenticator, Authy, etc.):",
            security2FA: "Security (2FA)",
            settings: "Settings",
            signInWithGoogle: "Sign in with Google",
            signUp: "Sign Up",
            signUpWithGoogle: "Sign Up with Google",
            status: "Status",
            tournament: "Tournament",
            tournamentSize: "Tournament size",
            twoFactorAuth: "Two-Factor Authentication",
            twoFactorDisabled: "Disabled",
            twoFactorDisabledSuccess: "Two-Factor Authentication has been disabled",
            twoFactorEnabled: "Enabled",
            twoFactorEnabledSuccess: "Two-Factor Authentication has been enabled!",
            twoFactorExplanation: "Two-Factor Authentication adds an extra layer of security to your account.",
            twoFactorProtected: "Your account is protected with Two-Factor Authentication.",
            use: "Use",
            username: "Username",
            usernameLengthError: "Username must be min 2 characters and max 15 characters",
            passwordLengthError: "Password must be min 8 characters and max 50 characters",
            emailLengthError: "Email can't be over 30 characters",
            verificationCode: "Verification Code",
            verify: "Verify",
            verifyAndEnable: "Verify & Enable",
            victory: "Victory",
            wantToLogOut: "Want to log out?",
            win: "Win",
            wins: "Wins",
        },
        "fr": {
            add: "Ajouter",
            alreadyRegistered: "Déjà inscrit ? Connectez-vous !",
            back: "Retour",
            backToHome: "Retour à l'accueil",
            cancel: "Annuler",
            changeAvatar: "Changer l'avatar",
            chooseAvatar: "Choisir un avatar",
            chooseSize: "Choisir la taille",
            connecting: "Connexion en cours...",
            couldNotConnectToServer: "Impossible de se connecter au serveur",
            createNewUser: "Créer un nouvel utilisateur",
            defeat: "Défaite",
            disable: "Désactiver",
            disableTwoFactor: "Désactiver l'authentification à deux facteurs",
            displayName: "Nom d'affichage",
            duplicateUser: "Cet utilisateur est déjà connecté. Veuillez choisir un autre compte.",
            edit: "Modifier",
            email: "Email",
            enable: "Activer",
            enableTwoFactor: "Activer l'authentification à deux facteurs",
            enterImageUrl: "Entrez une URL d'image",
            enterImageUrlPlaceholder: "https://exemple.com/mon-avatar.png",
            enterSixDigitCode: "Entrez le code à 6 chiffres de votre application d'authentification",
            failedToLoadProfile: "Échec du chargement du profil",
            findPeople: "Trouver des personnes",
            fourPlayers: "4 joueurs",
            friends: "Amis",
            howDoYouWantToPlay: "Comment voulez-vous jouer ?",
            incoming: "Entrant",
            intro: "Préparez-vous à jouer !",
            invalidCode: "Code invalide. Veuillez réessayer.",
            loading: "Chargement...",
            logIn: "Connexion",
            login: "Connexion",
            logOut: "Se déconnecter",
            logout: "Se déconnecter",
            loginOrSignupPlayer: "Connexion ou Inscription Joueur",
            loss: "Défaite",
            losses: "Défaites",
            manualEntry: "Ou entrez ce secret manuellement :",
            matchHistory: "Historique des matchs",
            memberSince: "Membre depuis le",
            next: "Suivant",
            noFriendsYet: "Pas encore d'amis",
            noGamesYet: "Aucun match joué pour le moment.",
            noNewUsersFound: "Aucun nouvel utilisateur trouvé.",
            noRequests: "Aucune demande",
            notRegisteredYet: "Pas encore inscrit ? Inscrivez-vous !",
            oneVsOne: "1 contre 1",
            or: "OU",
            outgoing: "Sortant",
            password: "Mot de passe",
            pleaseLoginToViewProfile: "Veuillez vous connecter pour voir votre profil",
            popupBlocked: "Popup bloquée. Veuillez autoriser les popups.",
            profile: "Profil",
            removeFriendConfirm: "Supprimer cet ami ?",
            requests: "Demandes",
            save: "Enregistrer",
            scanQRCode: "Scannez ce code QR avec votre application d'authentification (Google Authenticator, Authy, etc.) :",
            security2FA: "Sécurité (2FA)",
            settings: "Paramètres",
            signInWithGoogle: "Se connecter avec Google",
            signUp: "S'inscrire",
            signUpWithGoogle: "S'inscrire avec Google",
            status: "Statut",
            tournament: "Tournoi",
            tournamentSize: "Taille du tournoi",
            twoFactorAuth: "Authentification à deux facteurs",
            twoFactorDisabled: "Désactivée",
            twoFactorDisabledSuccess: "L'authentification à deux facteurs a été désactivée",
            twoFactorEnabled: "Activée",
            twoFactorEnabledSuccess: "L'authentification à deux facteurs a été activée !",
            twoFactorExplanation: "L'authentification à deux facteurs ajoute une couche de sécurité supplémentaire à votre compte.",
            twoFactorProtected: "Votre compte est protégé par l'authentification à deux facteurs.",
            use: "Utiliser",
            username: "Nom d'utilisateur",
            usernameLengthError: "Le nom d'utilisateur doit contenir entre 2 et 15 caractères",
            passwordLengthError: "Le mot de passe doit contenir entre 8 et 50 caractères",
            emailLengthError: "L'email ne peut pas dépasser 30 caractères",
            verificationCode: "Code de vérification",
            verify: "Vérifier",
            verifyAndEnable: "Vérifier et activer",
            victory: "Victoire",
            wantToLogOut: "Voulez-vous vous déconnecter ?",
            win: "Victoire",
            wins: "Victoires",
        },
        "fi": {
            add: "Lisää",
            alreadyRegistered: "Oletko jo rekisteröitynyt? Kirjaudu sisään!",
            back: "Takaisin",
            backToHome: "Takaisin kotiin",
            cancel: "Peruuta",
            changeAvatar: "Vaihda avatar",
            chooseAvatar: "Valitse avatar",
            chooseSize: "Valitse koko",
            connecting: "Yhdistetään...",
            couldNotConnectToServer: "Yhteyttä palvelimeen ei voitu muodostaa",
            createNewUser: "Luo uusi käyttäjä",
            defeat: "Tappio",
            disable: "Poista käytöstä",
            disableTwoFactor: "Poista kaksivaiheinen tunnistautuminen käytöstä",
            displayName: "Näyttönimi",
            duplicateUser: "Tämä käyttäjä on jo kirjautunut sisään. Käytä eri tiliä.",
            edit: "Muokkaa",
            email: "Sähköposti",
            enable: "Ota käyttöön",
            enableTwoFactor: "Ota kaksivaiheinen tunnistautuminen käyttöön",
            enterImageUrl: "Anna kuvan URL",
            enterImageUrlPlaceholder: "https://esimerkki.com/minun-avatar.png",
            enterSixDigitCode: "Syötä 6-numeroinen koodi todennussovelluksestasi",
            failedToLoadProfile: "Profiilin lataaminen epäonnistui",
            findPeople: "Etsi henkilöitä",
            fourPlayers: "4 pelaajaa",
            friends: "Ystävät",
            howDoYouWantToPlay: "Miten haluat pelata?",
            incoming: "Saapuva",
            intro: "Valmistaudutaan pelaamaan!",
            invalidCode: "Virheellinen koodi. Yritä uudelleen.",
            loading: "Ladataan...",
            logIn: "Kirjaudu sisään",
            login: "Kirjaudu",
            logOut: "Kirjaudu ulos",
            logout: "Kirjaudu ulos",
            loginOrSignupPlayer: "Kirjaudu tai rekisteröidy pelaaja",
            loss: "Tappio",
            losses: "Tappiota",
            manualEntry: "Tai syötä tämä salaisuus manuaalisesti:",
            matchHistory: "Otteluhistoria",
            memberSince: "Jäsen alkaen",
            next: "Seuraava",
            noFriendsYet: "Ei vielä ystäviä",
            noGamesYet: "Ei pelattuja pelejä vielä.",
            noNewUsersFound: "Uusia käyttäjiä ei löytynyt.",
            noRequests: "Ei pyyntöjä",
            notRegisteredYet: "Etkö ole vielä rekisteröitynyt? Rekisteröidy!",
            oneVsOne: "1 vastaan 1",
            or: "TAI",
            outgoing: "Lähtevä",
            password: "Salasana",
            pleaseLoginToViewProfile: "Kirjaudu sisään nähdäksesi profiilisi",
            popupBlocked: "Ponnahdusikkuna estetty. Salli ponnahdusikkunat.",
            profile: "Profiili",
            removeFriendConfirm: "Poista tämä ystävä?",
            requests: "Pyynnöt",
            save: "Tallenna",
            scanQRCode: "Skannaa tämä QR-koodi todennussovelluksellasi (Google Authenticator, Authy, jne.):",
            security2FA: "Turvallisuus (2FA)",
            settings: "Asetukset",
            signInWithGoogle: "Kirjaudu Googlella",
            signUp: "Rekisteröidy",
            signUpWithGoogle: "Rekisteröidy Googlella",
            status: "Tila",
            tournament: "Turnaus",
            tournamentSize: "Turnauksen koko",
            twoFactorAuth: "Kaksivaiheinen tunnistautuminen",
            twoFactorDisabled: "Pois käytöstä",
            twoFactorDisabledSuccess: "Kaksivaiheinen tunnistautuminen on poistettu käytöstä",
            twoFactorEnabled: "Käytössä",
            twoFactorEnabledSuccess: "Kaksivaiheinen tunnistautuminen on otettu käyttöön!",
            twoFactorExplanation: "Kaksivaiheinen tunnistautuminen lisää ylimääräisen turvallisuustason tilillesi.",
            twoFactorProtected: "Tilisi on suojattu kaksivaiheisella tunnistautumisella.",
            use: "Käytä",
            username: "Käyttäjänimi",
            usernameLengthError: "Käyttäjänimen tulee olla vähintään 2 ja enintään 15 merkkiä",
            passwordLengthError: "Salasanan tulee olla vähintään 8 ja enintään 50 merkkiä",
            emailLengthError: "Sähköposti ei voi olla yli 30 merkkiä",
            verificationCode: "Vahvistuskoodi",
            verify: "Vahvista",
            verifyAndEnable: "Vahvista ja ota käyttöön",
            victory: "Voitto",
            wantToLogOut: "Haluatko kirjautua ulos?",
            win: "Voitto",
            wins: "Voittoa",
        },
        "ru": {
            add: "Добавить",
            alreadyRegistered: "Уже зарегистрированы? Войдите!",
            back: "Назад",
            backToHome: "Вернуться на главную",
            cancel: "Отмена",
            changeAvatar: "Изменить аватар",
            chooseAvatar: "Выбрать аватар",
            chooseSize: "Выберите размер",
            connecting: "Подключение...",
            couldNotConnectToServer: "Не удалось подключиться к серверу",
            createNewUser: "Создать нового пользователя",
            defeat: "Поражение",
            disable: "Отключить",
            disableTwoFactor: "Отключить двухфакторную аутентификацию",
            displayName: "Отображаемое имя",
            duplicateUser: "Этот пользователь уже вошел в систему. Пожалуйста, используйте другую учетную запись.",
            edit: "Изменить",
            email: "Электронная почта",
            enable: "Включить",
            enableTwoFactor: "Включить двухфакторную аутентификацию",
            enterImageUrl: "Введите URL изображения",
            enterImageUrlPlaceholder: "https://example.com/мой-аватар.png",
            enterSixDigitCode: "Введите 6-значный код из вашего приложения для аутентификации",
            failedToLoadProfile: "Не удалось загрузить профиль",
            findPeople: "Найти людей",
            fourPlayers: "4 игрока",
            friends: "Друзья",
            howDoYouWantToPlay: "Как вы хотите играть?",
            incoming: "Входящие",
            intro: "Давайте приготовимся к игре!",
            invalidCode: "Неверный код. Попробуйте снова.",
            loading: "Загрузка...",
            logIn: "Вход",
            login: "Войти",
            logOut: "Выйти",
            logout: "Выйти",
            loginOrSignupPlayer: "Войти или зарегистрировать игрока",
            loss: "Поражение",
            losses: "Поражения",
            manualEntry: "Или введите этот секрет вручную:",
            matchHistory: "История матчей",
            memberSince: "Участник с",
            next: "Далее",
            noFriendsYet: "Пока нет друзей",
            noGamesYet: "Игр пока нет.",
            noNewUsersFound: "Новых пользователей не найдено.",
            noRequests: "Нет запросов",
            notRegisteredYet: "Ещё не зарегистрированы? Зарегистрируйтесь!",
            oneVsOne: "1 против 1",
            or: "ИЛИ",
            outgoing: "Исходящие",
            password: "Пароль",
            pleaseLoginToViewProfile: "Пожалуйста, войдите, чтобы увидеть свой профиль",
            popupBlocked: "Всплывающее окно заблокировано. Пожалуйста, разрешите всплывающие окна.",
            profile: "Профиль",
            removeFriendConfirm: "Удалить этого друга?",
            requests: "Запросы",
            save: "Сохранить",
            scanQRCode: "Отсканируйте этот QR-код с помощью вашего приложения для аутентификации (Google Authenticator, Authy и т.д.):",
            security2FA: "Безопасность (2FA)",
            settings: "Настройки",
            signInWithGoogle: "Войти через Google",
            signUp: "Регистрация",
            signUpWithGoogle: "Зарегистрироваться через Google",
            status: "Статус",
            tournament: "Турнир",
            tournamentSize: "Размер турнира",
            twoFactorAuth: "Двухфакторная аутентификация",
            twoFactorDisabled: "Отключена",
            twoFactorDisabledSuccess: "Двухфакторная аутентификация отключена",
            twoFactorEnabled: "Включена",
            twoFactorEnabledSuccess: "Двухфакторная аутентификация включена!",
            twoFactorExplanation: "Двухфакторная аутентификация добавляет дополнительный уровень защиты вашей учетной записи.",
            twoFactorProtected: "Ваша учетная запись защищена двухфакторной аутентификацией.",
            use: "Использовать",
            username: "Имя пользователя",
            usernameLengthError: "Имя пользователя должно содержать от 2 до 15 символов",
            passwordLengthError: "Пароль должен содержать от 8 до 50 символов",
            emailLengthError: "Электронная почта не может быть длиннее 30 символов",
            verificationCode: "Код подтверждения",
            verify: "Проверить",
            verifyAndEnable: "Проверить и включить",
            victory: "Победа",
            wantToLogOut: "Хотите выйти?",
            win: "Победа",
            wins: "Победы",
        }
    }
);

type Translations = typeof table.en;

// Non-hook function for use outside React components (e.g., utility functions)
export function t(): Translations {
    const supportedLanguages = ["en", "fi", "fr", "ru"] as const;
    let locale = document.documentElement.lang;
    if (!supportedLanguages.includes(locale as any)) {
        locale = "en";
    }
    return table[locale as keyof typeof table];
}

export const useLanguage = (): Translations => {
    const [, forceUpdate] = useState({});

    useEffect(() => {
        const handleLanguageChange = () => forceUpdate({});
        window.addEventListener('languageChange', handleLanguageChange);
        return () => window.removeEventListener('languageChange', handleLanguageChange);
    }, []);

    return t();
};
