import { useState, useEffect } from "react";

const table = Object.freeze(
    {
        "en": {
            alreadyRegistered: "Already registered? Login!",
            back: "Back",
            cancel: "Cancel",
            chooseSize: "Choose size",
            couldNotConnectToServer: "Could not connect to the server",
            createNewUser: "Create new user",
            disable: "Disable",
            disableTwoFactor: "Disable Two-Factor Authentication",
            duplicateUser: "This user is already logged in. Please use a different account.",
            email: "Email",
            enable: "Enable",
            enableTwoFactor: "Enable Two-Factor Authentication",
            enterSixDigitCode: "Enter the 6-digit code from your authenticator app",
            failedToLoadProfile: "Failed to load profile",
            fourPlayers: "4 players",
            howDoYouWantToPlay: "How do you want to play?",
            intro: "Let's get ready to play!",
            invalidCode: "Invalid code. Please try again.",
            loading: "Loading...",
            logIn: "Log In",
            logOut: "Log Out",
            loginOrSignupPlayer: "Login or Signup Player",
            manualEntry: "Or enter this secret manually:",
            next: "Next",
            notRegisteredYet: "Not registered yet? Sign up!",
            oneVsOne: "1 vs 1",
            password: "Password",
            scanQRCode: "Scan this QR code with your authenticator app (Google Authenticator, Authy, etc.):",
            settings: "Settings",
            signUp: "Sign Up",
            status: "Status",
            tournament: "Tournament",
            tournamentSize: "Tournament size",
            twoFactorAuth: "Two-Factor Authentication",
            twoFactorDisabled: "Disabled",
            twoFactorDisabledSuccess: "Two-Factor Authentication has been disabled",
            twoFactorEnabled: "Enabled",
            twoFactorEnabledSuccess: "Two-Factor Authentication has been enabled!",
            twoFactorExplanation: "Two-Factor Authentication adds an extra layer of security to your account.",
            twoFactorProtected: "Your account is protected with Two-Factor Authentication.",
            username: "Username",
            verificationCode: "Verification Code",
            verify: "Verify",
            verifyAndEnable: "Verify & Enable",
            wantToLogOut: "Want to log out?"
        },
        "fr": {
            alreadyRegistered: "Déjà inscrit ? Connectez-vous !",
            back: "Retour",
            cancel: "Annuler",
            chooseSize: "Choisir la taille",
            couldNotConnectToServer: "Impossible de se connecter au serveur",
            createNewUser: "Créer un nouvel utilisateur",
            disable: "Désactiver",
            disableTwoFactor: "Désactiver l'authentification à deux facteurs",
            duplicateUser: "Cet utilisateur est déjà connecté. Veuillez choisir un autre compte.",
            email: "Email",
            enable: "Activer",
            enableTwoFactor: "Activer l'authentification à deux facteurs",
            enterSixDigitCode: "Entrez le code à 6 chiffres de votre application d'authentification",
            failedToLoadProfile: "Échec du chargement du profil",
            fourPlayers: "4 joueurs",
            howDoYouWantToPlay: "Comment voulez-vous jouer ?",
            intro: "Préparez-vous à jouer !",
            invalidCode: "Code invalide. Veuillez réessayer.",
            loading: "Chargement...",
            logIn: "Connexion",
            logOut: "Se déconnecter",
            loginOrSignupPlayer: "Connexion ou Inscription Joueur",
            manualEntry: "Ou entrez ce secret manuellement :",
            next: "Suivant",
            notRegisteredYet: "Pas encore inscrit ? Inscrivez-vous !",
            oneVsOne: "1 contre 1",
            password: "Mot de passe",
            scanQRCode: "Scannez ce code QR avec votre application d'authentification (Google Authenticator, Authy, etc.) :",
            settings: "Paramètres",
            signUp: "S'inscrire",
            status: "Statut",
            tournament: "Tournoi",
            tournamentSize: "Taille du tournoi",
            twoFactorAuth: "Authentification à deux facteurs",
            twoFactorDisabled: "Désactivée",
            twoFactorDisabledSuccess: "L'authentification à deux facteurs a été désactivée",
            twoFactorEnabled: "Activée",
            twoFactorEnabledSuccess: "L'authentification à deux facteurs a été activée !",
            twoFactorExplanation: "L'authentification à deux facteurs ajoute une couche de sécurité supplémentaire à votre compte.",
            twoFactorProtected: "Votre compte est protégé par l'authentification à deux facteurs.",
            username: "Nom d'utilisateur",
            verificationCode: "Code de vérification",
            verify: "Vérifier",
            verifyAndEnable: "Vérifier et activer",
            wantToLogOut: "Voulez-vous vous déconnecter ?"
        },
        "fi": {
            alreadyRegistered: "Oletko jo rekisteröitynyt? Kirjaudu sisään!",
            back: "Takaisin",
            cancel: "Peruuta",
            chooseSize: "Valitse koko",
            couldNotConnectToServer: "Yhteyttä palvelimeen ei voitu muodostaa",
            createNewUser: "Luo uusi käyttäjä",
            disable: "Poista käytöstä",
            disableTwoFactor: "Poista kaksivaiheinen tunnistautuminen käytöstä",
            duplicateUser: "Tämä käyttäjä on jo kirjautunut sisään. Käytä eri tiliä.",
            email: "Sähköposti",
            enable: "Ota käyttöön",
            enableTwoFactor: "Ota kaksivaiheinen tunnistautuminen käyttöön",
            enterSixDigitCode: "Syötä 6-numeroinen koodi todennussovelluksestasi",
            failedToLoadProfile: "Profiilin lataaminen epäonnistui",
            fourPlayers: "4 pelaajaa",
            howDoYouWantToPlay: "Miten haluat pelata?",
            intro: "Valmistaudutaan pelaamaan!",
            invalidCode: "Virheellinen koodi. Yritä uudelleen.",
            loading: "Ladataan...",
            logIn: "Kirjaudu sisään",
            logOut: "Kirjaudu ulos",
            loginOrSignupPlayer: "Kirjaudu tai rekisteröidy pelaaja",
            manualEntry: "Tai syötä tämä salaisuus manuaalisesti:",
            next: "Seuraava",
            notRegisteredYet: "Etkö ole vielä rekisteröitynyt? Rekisteröidy!",
            oneVsOne: "1 vastaan 1",
            password: "Salasana",
            scanQRCode: "Skannaa tämä QR-koodi todennussovelluksellasi (Google Authenticator, Authy, jne.):",
            settings: "Asetukset",
            signUp: "Rekisteröidy",
            status: "Tila",
            tournament: "Turnaus",
            tournamentSize: "Turnauksen koko",
            twoFactorAuth: "Kaksivaiheinen tunnistautuminen",
            twoFactorDisabled: "Pois käytöstä",
            twoFactorDisabledSuccess: "Kaksivaiheinen tunnistautuminen on poistettu käytöstä",
            twoFactorEnabled: "Käytössä",
            twoFactorEnabledSuccess: "Kaksivaiheinen tunnistautuminen on otettu käyttöön!",
            twoFactorExplanation: "Kaksivaiheinen tunnistautuminen lisää ylimääräisen turvallisuustason tilillesi.",
            twoFactorProtected: "Tilisi on suojattu kaksivaiheisella tunnistautumisella.",
            username: "Käyttäjänimi",
            verificationCode: "Vahvistuskoodi",
            verify: "Vahvista",
            verifyAndEnable: "Vahvista ja ota käyttöön",
            wantToLogOut: "Haluatko kirjautua ulos?"
        },
        "ru": {
            alreadyRegistered: "Уже зарегистрированы? Войдите!",
            back: "Назад",
            cancel: "Отмена",
            chooseSize: "Выберите размер",
            couldNotConnectToServer: "Не удалось подключиться к серверу",
            createNewUser: "Создать нового пользователя",
            disable: "Отключить",
            disableTwoFactor: "Отключить двухфакторную аутентификацию",
            duplicateUser: "Этот пользователь уже вошел в систему. Пожалуйста, используйте другую учетную запись.",
            email: "Электронная почта",
            enable: "Включить",
            enableTwoFactor: "Включить двухфакторную аутентификацию",
            enterSixDigitCode: "Введите 6-значный код из вашего приложения для аутентификации",
            failedToLoadProfile: "Не удалось загрузить профиль",
            fourPlayers: "4 игрока",
            howDoYouWantToPlay: "Как вы хотите играть?",
            intro: "Давайте приготовимся к игре!",
            invalidCode: "Неверный код. Попробуйте снова.",
            loading: "Загрузка...",
            logIn: "Вход",
            logOut: "Выйти",
            loginOrSignupPlayer: "Войти или зарегистрировать игрока",
            manualEntry: "Или введите этот секрет вручную:",
            next: "Далее",
            notRegisteredYet: "Ещё не зарегистрированы? Зарегистрируйтесь!",
            oneVsOne: "1 против 1",
            password: "Пароль",
            scanQRCode: "Отсканируйте этот QR-код с помощью вашего приложения для аутентификации (Google Authenticator, Authy и т.д.):",
            settings: "Настройки",
            signUp: "Регистрация",
            status: "Статус",
            tournament: "Турнир",
            tournamentSize: "Размер турнира",
            twoFactorAuth: "Двухфакторная аутентификация",
            twoFactorDisabled: "Отключена",
            twoFactorDisabledSuccess: "Двухфакторная аутентификация отключена",
            twoFactorEnabled: "Включена",
            twoFactorEnabledSuccess: "Двухфакторная аутентификация включена!",
            twoFactorExplanation: "Двухфакторная аутентификация добавляет дополнительный уровень защиты вашей учетной записи.",
            twoFactorProtected: "Ваша учетная запись защищена двухфакторной аутентификацией.",
            username: "Имя пользователя",
            verificationCode: "Код подтверждения",
            verify: "Проверить",
            verifyAndEnable: "Проверить и включить",
            wantToLogOut: "Хотите выйти?"
        }
    }
);

type Translations = typeof table.en;

// Non-hook function for use outside React components (e.g., utility functions)
export function t(): Translations {
    const supportedLanguages = ["en", "fi", "fr", "ru"] as const;
    let locale = document.documentElement.lang;
    if (!supportedLanguages.includes(locale as any)) {
        locale = "en";
    }
    return table[locale as keyof typeof table];
}

export const useLanguage = (): Translations => {
    const [, forceUpdate] = useState({});

    useEffect(() => {
        const handleLanguageChange = () => forceUpdate({});
        window.addEventListener('languageChange', handleLanguageChange);
        return () => window.removeEventListener('languageChange', handleLanguageChange);
    }, []);

    return t();
};
